var firstname = window.prompt('What is your first name?')
var lastname = window.prompt('What is your last name?')
var age = window.prompt('What is your age?')
console.log('Your full name is', firstname, lastname)
console.log('You are', age, 'years old')
