var firstname = prompt("What is your first name?")
var lastname = prompt("What is your last name?")
var age = prompt("What is your age?")
console.log("Your full name is", firstname, lastname)
console.log("You are", age, "years old")